# Generated by Django 6.0.2 on 2026-02-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_percentage', models.FloatField(default=0.0, verbose_name='نسبة المشاهدة (%)')),
                ('last_second', models.PositiveIntegerField(default=0, verbose_name='آخر ثانية وصل إليها')),
                ('video_completed', models.BooleanField(db_index=True, default=False, verbose_name='الفيديو مكتمل (100%)')),
                ('homework_submitted', models.BooleanField(db_index=True, default=False, verbose_name='الواجب مسلّم')),
                ('homework_graded', models.BooleanField(default=False, verbose_name='الواجب متصحح')),
                ('lesson_completed', models.BooleanField(db_index=True, default=False, help_text='يصبح True تلقائياً عند video_completed AND homework_submitted', verbose_name='الدرس مكتمل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'تقدم الدرس',
                'verbose_name_plural': 'تقدم الدروس',
                'ordering': ['lesson__order'],
            },
        ),
    ]
