# Generated by Django 6.0.2 on 2026-02-10 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='تم تفعيل الاشتراك')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'قائمة الاشتراكات',
                'unique_together': {('student', 'teacher')},
            },
        ),
    ]
