# Generated by Django 6.0.2 on 2026-02-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='serial_number',
        ),
    ]
