# Generated by Django 6.0.2 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_created_at_alter_enrollment_enrolled_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course", "is_active", "is_pending", "expiry_date"],
                name="enrollment_active_idx",
            ),
        ),
    ]
