# Generated by Django 6.0.2 on 2026-02-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='صورة الغلاف')),
                ('access_type', models.CharField(choices=[('FREE', 'مجاني (كل الدروس متاحة)'), ('SEQUENTIAL', 'تسلسلي (يفتح درس درس)')], db_index=True, default='FREE', max_length=20, verbose_name='نوع الوصول')),
                ('has_trial', models.BooleanField(default=False, verbose_name='يحتوي على حصة تجريبية')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الوحدة')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='الترتيب')),
                ('has_unit_exam', models.BooleanField(default=False, verbose_name='تحتوي على امتحان وحدة')),
            ],
            options={
                'verbose_name': 'وحدة دراسية',
                'verbose_name_plural': 'الوحدات الدراسية',
                'ordering': ['order'],
            },
        ),
    ]
