# Generated by Django 6.0.2 on 2026-02-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='unit',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='courses.course'),
        ),
        migrations.AddField(
            model_name='unit',
            name='teacher',
            field=models.ForeignKey(help_text='المالك الأساسي لهذا السجل', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['course', 'order'], name='courses_uni_course__5a010f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('course', 'order')},
        ),
    ]
