# Generated by Django 6.0.2 on 2026-02-27 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('students', '0002_initial'),
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='كود التفعيل')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='مستخدم')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الاستخدام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإنشاء')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='courses.course', verbose_name='الكورس')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_codes', to='teachers.teacher', verbose_name='المدرس')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to='students.student', verbose_name='الطالب المستخدم')),
            ],
            options={
                'verbose_name': 'كود تفعيل',
                'verbose_name_plural': 'أكواد التفعيل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', 'is_used'], name='courses_act_course__761e14_idx'), models.Index(fields=['created_by', 'course'], name='courses_act_created_4005bc_idx')],
            },
        ),
    ]
