# Generated by Django 6.0.2 on 2026-02-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_activationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
