# Generated by Django 6.0.2 on 2026-02-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='صورة البروفايل'),
        ),
        migrations.AddField(
            model_name='user',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
