# Generated by Django 6.0.2 on 2026-03-03 00:00

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_is_active_alter_user_phone"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                Lower("email"),
                name="unique_user_email_ci",
            ),
        ),
    ]
