# Generated by Django 6.0.2 on 2026-02-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الشريك')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('revenue_share_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة الأرباح')),
            ],
            options={
                'verbose_name': 'شريك',
                'verbose_name_plural': 'الشركاء',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='السيرة الذاتية')),
                ('website_url', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('bunny_stream_api_key', models.CharField(blank=True, help_text='مفتاح API للبث', max_length=255, null=True)),
                ('bunny_storage_api_key', models.CharField(blank=True, help_text='مفتاح API للتخزين', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مدرس',
                'verbose_name_plural': 'المدرسين',
            },
        ),
    ]
