# Generated by Django 6.0.2 on 2026-02-23 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teachers.service'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='partner',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='follow',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='teachergroup',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='teachergroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teachers.teachergroup'),
        ),
        migrations.AddField(
            model_name='teachergroupmember',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='teacherreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherreview',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='teacherservicepurchase',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='teachers.service'),
        ),
        migrations.AddField(
            model_name='teacherservicepurchase',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_purchases', to='teachers.teacher'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['teacher', '-created_at'], name='teachers_fo_teacher_acfe81_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'teacher'), name='unique_follow'),
        ),
        migrations.AlterUniqueTogether(
            name='teachergroupmember',
            unique_together={('group', 'student')},
        ),
        migrations.AddIndex(
            model_name='teacherreview',
            index=models.Index(fields=['teacher', '-created_at'], name='teachers_te_teacher_489705_idx'),
        ),
    ]
