# Generated by Django 6.0.2 on 2026-02-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='نص الخيار')),
                ('is_correct', models.BooleanField(default=False, verbose_name='الإجابة الصحيحة')),
            ],
            options={
                'verbose_name': 'خيار',
                'verbose_name_plural': 'الخيارات',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدة الامتحان (دقائق)')),
                ('pass_score', models.PositiveIntegerField(default=50, help_text='درجة النجاح (نسبة مئوية)', verbose_name='درجة النجاح %')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امتحان',
                'verbose_name_plural': 'الامتحانات',
            },
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'جارٍ'), ('submitted', 'تم التسليم'), ('graded', 'تم التصحيح'), ('pending_manual_grading', 'في انتظار التصحيح اليدوي')], default='in_progress', max_length=30, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم')),
                ('mcq_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='درجة MCQ')),
                ('essay_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='درجة المقالي')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الدرجة الكلية')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='النسبة المئوية')),
                ('passed', models.BooleanField(default=False, verbose_name='ناجح')),
            ],
            options={
                'verbose_name': 'تسليم امتحان',
                'verbose_name_plural': 'تسليمات الامتحانات',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('question_type', models.CharField(choices=[('mcq', 'اختيار من متعدد'), ('essay', 'مقالي')], default='mcq', max_length=10, verbose_name='نوع السؤال')),
                ('marks', models.PositiveIntegerField(default=1, verbose_name='الدرجات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_text', models.TextField(blank=True, verbose_name='إجابة مقالية')),
                ('essay_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='درجة المقالي (يدوي)')),
                ('teacher_feedback', models.TextField(blank=True, verbose_name='ملاحظة المدرس')),
                ('is_correct', models.BooleanField(null=True, verbose_name='صحيحة')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.choice', verbose_name='الخيار المختار')),
            ],
            options={
                'verbose_name': 'إجابة',
                'verbose_name_plural': 'الإجابات',
            },
        ),
    ]
