# Generated by Django 6.0.2 on 2026-02-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='lesson',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='lessons.lesson', verbose_name='الدرس'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam', verbose_name='الامتحان'),
        ),
    ]
