# Generated by Django 6.0.2 on 2026-02-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to='students.student', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsubmission', verbose_name='التسليم'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='الامتحان'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question', verbose_name='السؤال'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.question', verbose_name='السؤال'),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['exam', 'student'], name='exams_exams_exam_id_46d7a6_idx'),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['status'], name='exams_exams_status_07f247_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
    ]
