# Generated by Django 6.0.2 on 2026-02-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='نشط'),
        ),
    ]
