# Generated by Django 6.0.2 on 2026-02-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الدرس')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدرس')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('bunny_video_id', models.CharField(blank=True, help_text='معرف الفيديو من Bunny Stream', max_length=255, null=True)),
                ('bunny_library_id', models.CharField(blank=True, help_text='معرف المكتبة من Bunny Stream', max_length=255, null=True)),
                ('lesson_material', models.FileField(blank=True, null=True, upload_to='lesson_materials/%Y/%m/', verbose_name='ملف الدرس (PDF)')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
