# Generated by Django 6.0.2 on 2026-02-23 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('bunny_video_id', models.CharField(blank=True, max_length=255, null=True)),
                ('lesson_material', models.FileField(blank=True, null=True, upload_to='lesson_materials/%Y/%m/')),
                ('is_trial', models.BooleanField(db_index=True, default=False, help_text='أي شخص يمكنه مشاهدة هذه الحصة بدون اشتراك', verbose_name='حصة تجريبية')),
                ('is_force_open', models.BooleanField(db_index=True, default=False, help_text='يفتح هذا الدرس حتى لو الدروس السابقة لم تكتمل (مثلاً درس مراجعة)', verbose_name='فتح إجباري')),
                ('publish_date', models.DateField(blank=True, help_text='إذا كان محدداً، لن يظهر الدرس قبل هذا التاريخ', null=True, verbose_name='تاريخ النشر')),
                ('has_homework', models.BooleanField(default=False, verbose_name='يحتوي على واجب')),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
