# Generated by Django 6.0.2 on 2026-02-09 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(help_text='المالك الأساسي لهذا السجل', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='teachers.teacher'),
        ),
    ]
