# Generated by Django 6.0.2 on 2026-02-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('lessons', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(help_text='المالك الأساسي لهذا السجل', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.unit', verbose_name='الوحدة الدراسية'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'is_published'], name='lessons_les_course__16a2e5_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order'], name='lessons_les_course__5adb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'is_trial'], name='lessons_les_course__8e84bb_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'is_force_open'], name='lessons_les_course__65d066_idx'),
        ),
    ]
