# Generated by Django 6.0.2 on 2026-02-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
