# Generated by Django 6.0.2 on 2026-02-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('post', 'منشور جديد'), ('comment', 'تعليق جديد'), ('like', 'إعجاب بمنشور'), ('expiry', 'انتهاء الاشتراك'), ('subscription_expired', 'اشتراك منتهي'), ('broadcast', 'رسالة جماعية'), ('system', 'تنبيه نظام')], db_index=True, default='system', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
