# Generated by Django 6.0.2 on 2026-03-03 00:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="dedupe_key",
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("user", "dedupe_key"),
                condition=Q(dedupe_key__isnull=False),
                name="unique_notification_dedupe_per_user",
            ),
        ),
    ]
