# Generated by Django 6.0.2 on 2026-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_dedupe_key"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_427e4b_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_user_id_05b4bc_idx",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notif_user_read_created_idx",
            ),
        ),
    ]
